const express=require('express');const fs=require('fs');const path=require('path');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const {getStore}=require('@netlify/blobs');
const app=express();const DB=path.join(__dirname,'data.json');const SECRET=process.env.JWT_SECRET;const serverless=Boolean(process.env.NETLIFY||process.env.NETLIFY_DEV||process.env.CONTEXT||process.env.AWS_LAMBDA_FUNCTION_NAME||process.env.LAMBDA_TASK_ROOT);
const seed={settings:{storeName:'Nepkits Hub',tagline:'Jerseys. Streetwear. Nepal.',logo:'/nepkits-hub-logo.svg',paymentQr:'',phone:'',email:'',instagram:''},users:[],products:[{id:1,name:'Nepal Home Jersey 2026',cat:'Jerseys',price:1499,stock:30,image:'',active:true},{id:2,name:'Kathmandu Street Tee',cat:'T-Shirts',price:899,stock:40,image:'',active:true},{id:3,name:'Classic Training Hoodie',cat:'Hoodies',price:1899,stock:25,image:'',active:true}],orders:[]};
const localRead=()=>{if(serverless)throw Error('Local file storage disabled');if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify(seed));return JSON.parse(fs.readFileSync(DB,'utf8'))};const localWrite=d=>{if(serverless)throw Error('Local file storage disabled');fs.writeFileSync(DB,JSON.stringify(d))};
const store=()=>serverless?getStore('nepkits-hub-data'):null;const readData=async()=>{if(!serverless)return localRead();const s=store();let d=await s.get('data',{type:'json'});if(!d){d=JSON.parse(JSON.stringify(seed));await s.setJSON('data',d)}return d};const writeData=async d=>serverless?store().setJSON('data',d):localWrite(d);
async function ensureAdmin(){if(!SECRET)throw Error('JWT_SECRET is not configured');const d=await readData();if(!d.users.some(u=>u.role==='admin')){if(!process.env.ADMIN_EMAIL||!process.env.ADMIN_PASSWORD)throw Error('ADMIN_EMAIL and ADMIN_PASSWORD are not configured');d.users.push({id:1,name:'Store Admin',email:process.env.ADMIN_EMAIL.trim().toLowerCase(),passwordHash:await bcrypt.hash(process.env.ADMIN_PASSWORD,10),role:'admin'});await writeData(d)}}
app.use(express.json({limit:'2mb'}));app.use(express.static(__dirname));const makeToken=u=>jwt.sign({id:u.id,role:u.role,email:u.email},SECRET,{expiresIn:'7d'});const auth=(req,res,next)=>{try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),SECRET);next()}catch{res.status(401).json({message:'Authentication required'})}};const admin=(req,res,next)=>req.user?.role==='admin'?next():res.status(403).json({message:'Admin only'});
app.get('/api/health',async(req,res)=>{try{await ensureAdmin();res.json({ok:true,storage:serverless?'netlify-blobs':'local'})}catch(e){res.status(500).json({ok:false,message:e.message})}});
app.get('/api/products',async(req,res)=>{try{res.json((await readData()).products.filter(x=>x.active!==false))}catch(e){res.status(500).json({message:e.message})}});app.get('/api/store/settings',async(req,res)=>{try{res.json((await readData()).settings)}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/auth/register',async(req,res)=>{try{const d=await readData(),name=String(req.body?.name||'').trim(),email=String(req.body?.email||'').trim().toLowerCase(),password=req.body?.password||'';if(!name||!email||password.length<6)return res.status(400).json({message:'Invalid registration'});if(d.users.some(x=>x.email===email))return res.status(409).json({message:'Email already registered'});const u={id:Date.now(),name,email,passwordHash:await bcrypt.hash(password,10),role:'customer'};d.users.push(u);await writeData(d);res.json({token:makeToken(u),user:{id:u.id,name,email,role:u.role}})}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{await ensureAdmin();const d=await readData(),email=String(req.body?.email||'').trim().toLowerCase(),u=d.users.find(x=>x.email===email);if(!u||!(await bcrypt.compare(req.body?.password||'',u.passwordHash)))return res.status(401).json({message:'Invalid email or password'});res.json({token:makeToken(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/orders/my',auth,async(req,res)=>{try{res.json((await readData()).orders.filter(o=>o.userId===req.user.id))}catch(e){res.status(500).json({message:e.message})}});app.post('/api/orders',auth,async(req,res)=>{try{const d=await readData(),o={id:'NH-'+Date.now().toString().slice(-8),userId:req.user.id,date:new Date().toISOString(),customer:req.body?.customer,items:req.body?.items||[],total:Number(req.body?.total||0),status:'Pending review',paymentProof:req.body?.paymentProof||''};d.orders.unshift(o);await writeData(d);res.status(201).json(o)}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/admin/stats',auth,admin,async(req,res)=>{try{const d=await readData();res.json({products:d.products.filter(x=>x.active!==false).length,orders:d.orders.length,customers:d.users.filter(x=>x.role==='customer').length,revenue:d.orders.filter(x=>x.status!=='Cancelled').reduce((s,x)=>s+x.total,0),pending:d.orders.filter(x=>!['Delivered','Cancelled'].includes(x.status)).length,lowStock:d.products.filter(x=>x.stock<=5).length})}catch(e){res.status(500).json({message:e.message})}});
app.get('/api/admin/orders',auth,admin,async(req,res)=>{try{res.json((await readData()).orders)}catch(e){res.status(500).json({message:e.message})}});app.get('/api/admin/products',auth,admin,async(req,res)=>{try{res.json((await readData()).products)}catch(e){res.status(500).json({message:e.message})}});
app.patch('/api/admin/orders/:id',auth,admin,async(req,res)=>{try{const d=await readData(),o=d.orders.find(x=>x.id===req.params.id);if(!o)return res.sendStatus(404);o.status=req.body?.status;await writeData(d);res.json(o)}catch(e){res.status(500).json({message:e.message})}});app.patch('/api/admin/products/:id',auth,admin,async(req,res)=>{try{const d=await readData(),p=d.products.find(x=>x.id===Number(req.params.id));if(!p)return res.sendStatus(404);Object.assign(p,req.body||{});await writeData(d);res.json(p)}catch(e){res.status(500).json({message:e.message})}});app.post('/api/admin/products',auth,admin,async(req,res)=>{try{const d=await readData(),p={id:Date.now(),name:req.body?.name,cat:req.body?.cat||'Jerseys',price:Number(req.body?.price||0),stock:Number(req.body?.stock||0),image:req.body?.image||'',active:true};d.products.push(p);await writeData(d);res.status(201).json(p)}catch(e){res.status(500).json({message:e.message})}});app.patch('/api/admin/settings',auth,admin,async(req,res)=>{try{const d=await readData();d.settings={...d.settings,...(req.body||{})};await writeData(d);res.json(d.settings)}catch(e){res.status(500).json({message:e.message})}});
if(require.main===module)app.listen(process.env.PORT||3000,()=>console.log('Nepkits Hub running'));module.exports=app;