const express=require('express');const path=require('path');const fs=require('fs');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');
const app=express();const DB=path.join(__dirname,'data.json');const SECRET=process.env.JWT_SECRET||'CHANGE_ME_IN_NETLIFY';
const seed={settings:{storeName:'Nepkits Hub',tagline:'Jerseys. Streetwear. Nepal.',logo:'/nepkits-hub-logo.svg',paymentQr:'',phone:'',email:'',instagram:''},users:[],products:[{id:1,name:'Nepal Home Jersey 2026',cat:'Jerseys',price:1499,stock:30,image:'',active:true},{id:2,name:'Kathmandu Street Tee',cat:'T-Shirts',price:899,stock:40,image:'',active:true},{id:3,name:'Classic Training Hoodie',cat:'Hoodies',price:1899,stock:25,image:'',active:true}],orders:[]};
if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify(seed,null,2));const read=()=>JSON.parse(fs.readFileSync(DB));const write=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));
let initial=read();if(!initial.users.some(u=>u.role==='admin')){initial.users.push({id:1,name:'Store Admin',email:(process.env.ADMIN_EMAIL||'admin@nepkitshub.com').toLowerCase(),passwordHash:bcrypt.hashSync(process.env.ADMIN_PASSWORD||'admin123',10),role:'admin'});write(initial)}
app.use(express.json());app.use(express.static(__dirname));function token(u){return jwt.sign({id:u.id,role:u.role,email:u.email},SECRET,{expiresIn:'7d'})}function auth(req,res,next){const t=(req.headers.authorization||'').replace('Bearer ','');try{req.user=jwt.verify(t,SECRET);next()}catch{res.status(401).json({message:'Authentication required'})}}function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({message:'Admin only'});next()}
app.get('/api/health',(q,r)=>r.json({ok:true}));app.get('/api/products',(q,r)=>r.json(read().products.filter(x=>x.active!==false)));app.get('/api/store/settings',(q,r)=>r.json(read().settings));
app.post('/api/auth/register',(q,r)=>{let d=read(),{name,email,password}=q.body;if(!name||!email||!password||password.length<6)return r.status(400).json({message:'Invalid registration'});if(d.users.some(x=>x.email===email.toLowerCase()))return r.status(409).json({message:'Email already registered'});let u={id:Date.now(),name,email:email.toLowerCase(),passwordHash:bcrypt.hashSync(password,10),role:'customer'};d.users.push(u);write(d);r.json({token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.post('/api/auth/login',(q,r)=>{let d=read(),u=d.users.find(x=>x.email===String(q.body.email||'').toLowerCase());if(!u||!bcrypt.compareSync(q.body.password||'',u.passwordHash))return r.status(401).json({message:'Invalid email or password'});r.json({token:token(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/orders/my',auth,(q,r)=>r.json(read().orders.filter(o=>o.userId===q.user.id)));app.post('/api/orders',auth,(q,r)=>{let d=read(),o={id:'NH-'+Date.now().toString().slice(-8),userId:q.user.id,date:new Date().toISOString(),customer:q.body.customer,items:q.body.items||[],total:Number(q.body.total||0),status:'Pending review',paymentProof:q.body.paymentProof||''};d.orders.unshift(o);write(d);r.status(201).json(o)});
app.get('/api/admin/stats',auth,admin,(q,r)=>{let d=read();r.json({products:d.products.filter(x=>x.active!==false).length,orders:d.orders.length,customers:d.users.filter(x=>x.role==='customer').length,revenue:d.orders.filter(x=>x.status!=='Cancelled').reduce((s,x)=>s+x.total,0),pending:d.orders.filter(x=>!['Delivered','Cancelled'].includes(x.status)).length,lowStock:d.products.filter(x=>x.stock<=5).length})});app.get('/api/admin/orders',auth,admin,(q,r)=>r.json(read().orders));app.get('/api/admin/products',auth,admin,(q,r)=>r.json(read().products));
app.patch('/api/admin/orders/:id',auth,admin,(q,r)=>{let d=read(),o=d.orders.find(x=>x.id===q.params.id);if(!o)return r.sendStatus(404);o.status=q.body.status;write(d);r.json(o)});app.patch('/api/admin/products/:id',auth,admin,(q,r)=>{let d=read(),p=d.products.find(x=>x.id===Number(q.params.id));if(!p)return r.sendStatus(404);Object.assign(p,q.body);write(d);r.json(p)});app.post('/api/admin/products',auth,admin,(q,r)=>{let d=read(),p={id:Date.now(),name:q.body.name,cat:q.body.cat||'Jerseys',price:Number(q.body.price||0),stock:Number(q.body.stock||0),image:q.body.image||'',active:true};d.products.push(p);write(d);r.status(201).json(p)});app.patch('/api/admin/settings',auth,admin,(q,r)=>{let d=read();d.settings={...d.settings,...q.body};write(d);r.json(d.settings)});
if(require.main===module)app.listen(process.env.PORT||3000,()=>console.log('Nepkits Hub running on http://localhost:'+(process.env.PORT||3000)));module.exports=app;
